- name: Check Connectivity
  hosts: mydroplet
  tasks:
  - name: Ping the hosts
    ping:
  - name: Echo Variables
    debug: 
      msg: "ansible_user {{ ansible_user }}"


- name: Setup server
  hosts: all
  vars:
    packages: 
      - name: nginx
        state: present
      - name: python3.8
        state: present
  tasks:
  - name: Install packages
    apt:
      name: "{{ item.name }}"
      update_cache: true
      state: "{{ item.state }}"
      autoremove: true
    loop: "{{packages}}"

  - name: check if /etc/hosts ecists
    stat:
      path: /etc/hosts
    register: host_file
  - name: dump host_file register
    debug:
      msg: " **** {{ host_file }}"